# Generated by Django 2.2.5 on 2019-09-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
